[package]
name = "vis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "*"
apodize = "*"
rodio = "*"
#apodize = "*"
#yt-api = "0.3.2"
crossterm = "*"